### ISSUE TITLE
Ensure Intake Form sections are properly hidden/shown according to the checkboxes (or if Contact is New)

### ISSUE THREAD

**Issue by evandana** [evandana/keep-ahope#20]
## Checkboxes default state

- [x] ~If Contact is new, then the "New" checkbox should be checked by default. Otherwise it's unchecked by default~ Ref #40 
- [x] Intake should always be checked by default and disabled (so it can't be changed) #36
- [x] Periodic should be unchecked by default #36

## Behavior

- [x] When a checkbox is checked, the appropriate questions for that section are shown, otherwise when it is unchecked, those questions are hidden. #36 
- [x] Only shown questions are submitted #36 
- [x] When a form is partially filled out and the questions for a section go from being shown to hidden and back to shown, the values should be consistent across both shown states. e.g. If you hide a section, it should not erase any filled out data. #36

**Comment by evandana** [comment]
Closing. Moving unfinished checkboxes to new issue (labeled above as Ref #40 )
